config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  namespace :admin do
    resources :cms_pages
    resources :blogs
    resources :products
    resources :sliders
    resources :categories do
      collection do
        get 'create_sub_category'
      end
  end

  end
    root 'home#index'
  resources :products
  resources :admin
   resources :cms_pages
   resources :contacts
   resources :blogs
   resources :api do
   end
   namespace :api do
    namespace :v1 do
    resources :categories, :defaults => { :format => :json } do
     member do
      get 'product'
    end
  end
  end
   end
   resources :carts do
  member do
    get 'cart_script'
   end
 end
   

end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/admin/cms_page.rb
class Admin::CmsPage < ActiveRecord::Base
has_attached_file :avatar, styles: {large: "458x606",normal: "253x337#",thumbnail: "72x72",small: "88x144",sidebar: "270x357" }
validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  include ActiveModel::Model
  include ActiveModel::Conversion
  include ActiveModel::Validations

  attr_accessor :name, :email, :description

  validates :name,
    presence: true

  validates :email,
    presence: true

  validates :description,
    presence: true
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
belongs_to :order
belongs_to :product
end

app/models/order.rb
class Order < ActiveRecord::Base
has_many :line_items
has_and_belongs_to_many :products
end

app/models/role.rb
# class Role < ActiveRecord::Base
#   has_and_belongs_to_many :users, :join_table => :users_roles

#   belongs_to :resource,
#              :polymorphic => true,
             

#   validates :resource_type,
#             :inclusion => { :in => Rolify.resource_types },
#             :allow_nil => true

#   scopify
# end

class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles

  belongs_to :resource,
             :polymorphic => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
	rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin/cms_pages_controller.rb
class Admin::CmsPagesController < AdminController
before_action :set_cms_page, only: [:show, :update, :edit, :destroy]
def index
	@cms_pages = Admin::CmsPage.all
end


def new
@cms_page = Admin::CmsPage.new
end


def create
@cms_page = Admin::CmsPage.new(cms_pages_params)
 respond_to do |format|
      if @cms_page.save
        format.html { redirect_to admin_cms_pages_path, notice: 'CMS Page was successfully created.' }
      else
        format.html { render :new }
        format.json { render json: @cms_page.errors, status: :unprocessable_entity }
      end
    end
end


def edit
end

def show
end

def update
respond_to do |format|
      if @cms_page.update(cms_pages_params)
        format.html { redirect_to admin_cms_pages_path, notice: 'CMS Page was successfully updated.' }
             else
        format.html { render :edit }
        format.json { render json: @cms_page.errors, status: :unprocessable_entity }
      end
    end
end


def destroy
	@cms_page = Admin::CmsPage.find(params[:id])
	@cms_page.destroy
	redirect_to admin_cms_pages_path
end

private

def set_cms_page
@cms_page = Admin::CmsPage.find(params[:id])
end


def cms_pages_params
 	params.require(:admin_cms_page).permit(:title, :description, :avatar)
end

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
	layout 'admin'
	protect_from_forgery with: :null_session
	skip_before_filter :verify_authenticity_token
protect_from_forgery prepend: true, with: :exception
before_action :authenticate_user!

	  before_filter :is_admin?

def is_admin?
		if current_user.has_role? 'admin'
  			@users = User.all
  			true
		
		else
  		render :text => 'Who are you to doing this? :)'
		sign_out current_user 
		end
	end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
protect_from_forgery with: :null_session
  before_action :cms_pages
  

  def cms_pages
  	@cms_pages = Admin::CmsPage.all
  	@contact = Contact.new
  	
  end

end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
def index
@admin_blogs = Admin::Blog.all
end

def show
	end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
def cart_script
	@product = Admin::Product.find(params[:id])

	@current_order = Order.create

	line_item = LineItem.create(params[:product_id => @product.id,:order_id => @current_order.id])
end
end

app/controllers/cms_pages_controller.rb
class CmsPagesController < ApplicationController

def index
@cms_pages = Admin::CmsPage.all
end

def show
@cms_page = Admin::CmsPage.find(params[:id])
end


end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

def index
end

def new
@contact = Contact.new
end

def create

# @contact = Contact.new(contact_params)
# respond_to do |format|
#       if @contact.save
#         format.html { redirect_to root_path, notice: 'Message sent successfully.' }
#     else
#         format.html { render :new }
#         format.json { render json: @contact.errors, status: :unprocessable_entity }
#     end
# end
# end


   @contact = Contact.new(contact_params)
    
    if @contact.valid?
      ContactMailer.new_message(@contact).deliver
      redirect_to root_path, notice: "Your messages has been sent."
    else
      flash[:alert] = "An error occurred while delivering this message."
      render :new
    end
  end




private

def contact_params
 params.require(:contact).permit(:name, :email, :description)

end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
def index
	 @admin_products = Admin::Product.all
	 @admin_sliders = Admin::Slider.all
end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
before_action :set_admin_product, only: [:show, :edit, :update, :destroy]
def index
	@admin_categories = Admin::Category.all
	if params[:category_id].present?
    @admin_products = Admin::Product.joins(:categories).where("admin_categories.id" => params[:category_id])
	else
	@admin_products = Admin::Product.all
end
end

def show
    @product = Admin::Product.find(params[:id])
    @admin_categories = Admin::Category.all
    if params[:category_id].present?
    @admin_products = Admin::Product.joins(:categories).where("admin_categories.id" => params[:category_id])
	else
	@admin_products = Admin::Product.all
end
end
private

    def set_admin_product
      @admin_product = Admin::Product.find(params[:id])
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/cms_pages/_all_cms_pages.html.erb
<div class="dataTable_wrapper">
    <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-vendors">
        <thead>
            <tr>
            <th style="display: none;"></th>
            
                <th><%= t 'admin.title'%></th>
                <th><%= t 'admin.description'%></th>
                <th><%= t 'admin.Image'%></th>
                  <th><%= t 'admin.tool'%></th>
                </tr>
        </thead>
        <tbody>
        
   <% @cms_pages.each do |page| %>
            <tr class="odd gradeX">
            <td style="display: none;"></td>
                <td><%= page.title %></td>
                <td><%= page.description %></td>
                <td><%= image_tag page.avatar.url(:thumbnail) %></td>
                <td>
                   <span>
                     <%= link_to '', edit_admin_cms_page_path(page),class: "edit fa fa-edit icon_link with-tip no-text", title: "edit" %> 
                      </span>
                    <span>
                        <%= link_to '',  admin_cms_page_path(page),  method: :delete, data: { confirm: 'Are you sure?' } ,class: "fa fa-trash icon_link with-tip no-text"%>
                     </span>
                </td> 
            </tr> 
                <%end%>                                                
        </tbody>
    </table>
</div>
<!-- /.table-responsive -->
<script>
    $(document).ready(function() {
        $('#dataTables-vendors').DataTable({
                responsive: true,
                pageLength: 50,
                autoWidth: false

        });
    });
</script>

app/views/admin/cms_pages/_newform.html.erb
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                New CMS Page
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-lg-6">
                        <%= form_for(@cms_page) do |f| %>
                            
                            <div class="form-group">
                               <%=f.label :title%>
                                <%=f.text_field :title ,class: 'form-control admin_cms_page ', placeholder: 'Enter title' , required: 'true'%>
                            </div>
                           
                            <div class="form-group">
                               <%=f.label :description%>
                                <%=f.cktext_area :description, class: 'form-control', placeholder: 'deccribe' , required: 'true' %>
                            </div>

                               <div class="form-group">
                               <%=f.label :Image%>
                                <%=f.file_field :avatar ,class: 'form-control'%>
                            </div>                             
                            <br>

                            <div><p><%= f.submit 'Submit', class: "btn btn-default" %>
                            
                            <button type="reset" class="btn btn-default">Reset Button</button></p></div>
                        <%end%>
                    </div>
                    <!-- /.col-lg-6 (nested) -->
                    
                </div>
                <!-- /.row (nested) -->
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->

app/views/admin/cms_pages/edit.html.erb
<h1>Editing CMS Page</h1>

<%= render 'newform' %>

app/views/admin/cms_pages/index.html.erb
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header"> All Products</h1>
    </div>
    <!-- /.col-lg-12 -->
    <div class="col-lg-12"><%= link_to 'New CMS Page', new_admin_cms_page_path %></div>
    
</div >
<!-- /.row -->
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div  id="admin_products">
                    <%=render :partial => 'all_cms_pages'%>
                    <!-- /.table-responsive -->
                </div> 
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->

app/views/cms_pages/show.html.erb
	<!-- header -->
			<!-- //header-top -->
			
	<!-- //header -->
	<!-- about -->
	<div class="about">
		<!-- container -->
		<div class="container">
			<div class="about-grids">
				<div class="col-md-4 about-left">
					<h3>Title: <%= @cms_page.title %></h3>
					<img src="<%= @cms_page.avatar.url(:original)%>" />
					<h5></h5>
					<p></p>
				</div>
				<div class="col-md-8 about-right">
					<h3>Description</h3>
					<h5></h5>
					<p><%= @cms_page.description.html_safe %></p>
				</div>
				
				<div class="clearfix"> </div>
			</div>
		</div>
		<!-- container -->
	</div>
	<!-- //about -->
	<!-- footer -->
	<div class="footer">
		<!-- container -->
		<div class="container">
			<div class="col-md-3 stores-grid">
				<div class="stores">
					<h3>Our Stores</h3>
					<ul>
							<li>Feel free to visit our stores.</li>
							<li>1234 South Grand Avenue </li>
							<li>Los Angeles, CA 00000 </li>
							<li>(123) 456-7890</li>
						<span>
							<li class="drive">123 Fairview Drive </li>
							<li>Area Name, VA 12345</li> 
							<li>(123) 456-7890</li>
						</span>
					</ul>
				</div>
				<div class="social-icons white-icons">
					<ul>
						<li><a href="#" class="facebook"></a></li>
						<li><a href="#" class="twitter"></a></li>
						<li><a href="#" class="chrome"></a></li>
						<li><a href="#" class="vimeo"></a></li>
						<li><a href="#" class="rss"></a></li>
				</div>
			</div>
			<div class="col-md-3 blog">
				<h3>Blog posts</h3>
				<a href="#">Post title goes here.</a>
				<p>Lorem ipsum dolor sit amet, consectetur
					adipiscing elit. Donec sed auctor elit.
				</p>
				<a href="#">Post title goes here.</a>
				<p>Lorem ipsum dolor sit amet, consectetur
					adipiscing elit. Donec sed auctor elit.
				</p>
				<a href="#">Winter sales are coming!</a>
				<p>Lorem ipsum dolor sit amet, consectetur
					adipiscing elit. Donec sed auctor elit.
				</p>
			</div>
			<div class="col-md-3 support">
				<h3>Support</h3>
				<div class="support-grids">
					<div class="support-left">
						<ul>
							<li><a href="#">Terms & Conditions</a></li>
							<li><a href="#">FAQ</a></li>
							<li><a href="#">Payment</a></li>
							<li><a href="#">Refunds</a></li>
							<li><a href="#">Track Order</a></li>
							<li><a href="#">Services</a></li>
							<li><a href="#">Privacy & Security</a></li>
							<li><a href="#">Careers</a></li>
							<li><a href="#">Press</a></li>
							<li><a href="#">Corporate Information</a></li>
						</ul>
					</div>
					<div class="support-left support-right">
						<ul>
							<li><a href="#">Sizing</a></li>
							<li><a href="#">Ordering</a></li>
							<li><a href="#">Shipping</a></li>
							<li><a href="#">Return Policy</a></li>
							<li><a href="#">Affiliates</a></li>
							<li><a href="#">Find A Store </a></li>
							<li><a href="#">Site Map</a></li>
							<li><a href="#">Sign Up & Save</a></li>
						</ul>
					</div>
					<div class="clearfix"> </div>
				</div>
			</div>
			<div class="col-md-3 contact">
				<h3>Contact us</h3>
				<form>
					<input type="text" value="email address" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'email address';}" required="">
					<textarea value="message:" onfocus="if(this.value == 'message') this.value='';" onblur="if(this.value == '') this.value='message';">message</textarea>
					<input type="submit" value="Send MESSAGE">
				</form>
			</div>
			<div class="clearfix"> </div>
			<div class="copyright">
				<p>&copy; 2015, PSHQ <a href="#">Furniture Template</a>. All rights reserved.</p>
			</p>
		</div>
		<!-- // container -->
	</div>
	<!-- //footer -->