config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  namespace :admin do
    resources :cms_pages
    resources :blogs
    resources :products
    resources :sliders
    resources :categories do
      collection do
        get 'create_sub_category'
      end
  end

  end
    root 'home#index'
  resources :products
  resources :admin
   resources :cms_pages
   resources :contacts
   resources :blogs
   resources :api do
   end
   namespace :api do
    namespace :v1 do
    resources :categories, :defaults => { :format => :json } do
     member do
      get 'product'
    end
  end
  end
   end
   resources :carts do
  member do
    get 'cart_script'
   end
 end
   

end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/admin/blog.rb
class Admin::Blog < ActiveRecord::Base
has_attached_file :avatar, styles: {large: "458x606",normal: "253x337#",thumbnail: "72x72",small: "88x144",sidebar: "270x357" }
validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
end

app/models/admin/product.rb
class Admin::Product < ActiveRecord::Base
has_and_belongs_to_many :categories 
has_attached_file :avatar, styles: {large: "458x606",normal: "253x337#",thumbnail: "72x72",small: "88x144",sidebar: "270x357" }
validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
accepts_nested_attributes_for :categories
has_many :line_items
has_and_belongs_to_many :orders



def avatar_url
        avatar.url(:large)
    end
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  include ActiveModel::Model
  include ActiveModel::Conversion
  include ActiveModel::Validations

  attr_accessor :name, :email, :description

  validates :name,
    presence: true

  validates :email,
    presence: true

  validates :description,
    presence: true
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
belongs_to :order
belongs_to :product
end

app/models/order.rb
class Order < ActiveRecord::Base
has_many :line_items
has_and_belongs_to_many :products
end

app/models/role.rb
# class Role < ActiveRecord::Base
#   has_and_belongs_to_many :users, :join_table => :users_roles

#   belongs_to :resource,
#              :polymorphic => true,
             

#   validates :resource_type,
#             :inclusion => { :in => Rolify.resource_types },
#             :allow_nil => true

#   scopify
# end

class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles

  belongs_to :resource,
             :polymorphic => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
	rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < AdminController
  before_action :set_admin_product, only: [:show, :edit, :update, :destroy]

  # GET /admin/products
  # GET /admin/products.json
  def index
  # Showing the Category products
      @admin_products = Admin::Product.all
  end

  # GET /admin/products/1
  # GET /admin/products/1.json
  def show
  end

  # GET /admin/products/new
  def new
    @admin_product = Admin::Product.new
  end

  # GET /admin/products/1/edit
  def edit
  end

  # POST /admin/products
  # POST /admin/products.json
  def create
    @admin_product = Admin::Product.new(admin_product_params)

    respond_to do |format|
      if @admin_product.save
        format.html { redirect_to admin_products_path, notice: 'Product was successfully created.' }
      else
        format.html { render :new }
        format.json { render json: @admin_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/products/1
  # PATCH/PUT /admin/products/1.json
  def update
    respond_to do |format|
      if @admin_product.update(admin_product_params)
        format.html { redirect_to admin_products_path, notice: 'Product was successfully updated.' }
      else
        format.html { render :edit }
        format.json { render json: @admin_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/products/1
  # DELETE /admin/products/1.json
  def destroy
    @admin_product = Admin::Product.find(params[:id])
    @admin_product.destroy

    redirect_to admin_products_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_product
      @admin_product = Admin::Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_product_params
      params.require(:admin_product).permit(:name, :price, :discounted_pric, :description, :avatar, category_ids: [])
    end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
	layout 'admin'
	protect_from_forgery with: :null_session
	skip_before_filter :verify_authenticity_token
protect_from_forgery prepend: true, with: :exception
before_action :authenticate_user!

	  before_filter :is_admin?

def is_admin?
		if current_user.has_role? 'admin'
  			@users = User.all
  			true
		
		else
  		render :text => 'Who are you to doing this? :)'
		sign_out current_user 
		end
	end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
protect_from_forgery with: :null_session
  before_action :cms_pages
  

  def cms_pages
  	@cms_pages = Admin::CmsPage.all
  	@contact = Contact.new
  	
  end

end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
def index
@admin_blogs = Admin::Blog.all
end

def show
	end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
def cart_script
	@product = Admin::Product.find(params[:id])

	@current_order = Order.create

	line_item = LineItem.create(params[:product_id => @product.id,:order_id => @current_order.id])
end
end

app/controllers/cms_pages_controller.rb
class CmsPagesController < ApplicationController

def index
@cms_pages = Admin::CmsPage.all
end

def show
@cms_page = Admin::CmsPage.find(params[:id])
end


end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

def index
end

def new
@contact = Contact.new
end

def create

# @contact = Contact.new(contact_params)
# respond_to do |format|
#       if @contact.save
#         format.html { redirect_to root_path, notice: 'Message sent successfully.' }
#     else
#         format.html { render :new }
#         format.json { render json: @contact.errors, status: :unprocessable_entity }
#     end
# end
# end


   @contact = Contact.new(contact_params)
    
    if @contact.valid?
      ContactMailer.new_message(@contact).deliver
      redirect_to root_path, notice: "Your messages has been sent."
    else
      flash[:alert] = "An error occurred while delivering this message."
      render :new
    end
  end




private

def contact_params
 params.require(:contact).permit(:name, :email, :description)

end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
def index
	 @admin_products = Admin::Product.all
	 @admin_sliders = Admin::Slider.all
end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
before_action :set_admin_product, only: [:show, :edit, :update, :destroy]
def index
	@admin_categories = Admin::Category.all
	if params[:category_id].present?
    @admin_products = Admin::Product.joins(:categories).where("admin_categories.id" => params[:category_id])
	else
	@admin_products = Admin::Product.all
end
end

def show
    @product = Admin::Product.find(params[:id])
    @admin_categories = Admin::Category.all
    if params[:category_id].present?
    @admin_products = Admin::Product.joins(:categories).where("admin_categories.id" => params[:category_id])
	else
	@admin_products = Admin::Product.all
end
end
private

    def set_admin_product
      @admin_product = Admin::Product.find(params[:id])
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/products/_all_products.html.erb
<div class="dataTable_wrapper">
    <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-vendors">
        <thead>
            <tr>
            <th style="display: none;"></th>
            
                <th><%= t 'admin.name'%></th>
                <th><%= t 'admin.price'%></th>
                <th><%= t 'admin.discounted price'%></th>
                <th><%= t 'admin.description'%></th>
                <th><%= t 'admin.Image'%></th>
                  <th><%= t 'admin.tool'%></th>
                </tr>
        </thead>
        <tbody>

        <% @admin_products.each do |product| %>

            <tr class="odd gradeX">
            <td style="display: none;"></td>
                <td><%= product.name %></td>
                <td><%= product.price %></td>
                <td><%= product.discounted_pric %></td>
                <td><%= product.description %></td>
                <td><%= image_tag product.avatar.url(:thumbnail) %></td>
                <td>
                   <span>
                     <%= link_to '', edit_admin_product_path(product),class: "edit fa fa-edit icon_link with-tip no-text", title: "edit" %> 
                      </span>
                    <span>
                        <%= link_to '',  admin_product_path(product),  method: :delete, data: { confirm: 'Are you sure?' } ,class: "fa fa-trash icon_link with-tip no-text"%>
                     </span>
                </td> 
            </tr> 
                <%end%>                                                                      
        </tbody>
    </table>
</div>
<!-- /.table-responsive -->
<script>
    $(document).ready(function() {
        $('#dataTables-vendors').DataTable({
                responsive: true,
                pageLength: 50,
                autoWidth: false

        });
    });
</script>

app/views/admin/products/_form.html.erb
<%= form_for(@admin_product) do |f| %>
  <% if @admin_product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin_product.errors.count, "error") %> prohibited this admin_product from being saved:</h2>

      <ul>
      <% @admin_product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/products/_newform.html.erb
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                New Product Form
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-lg-6">
                        <%= form_for(@admin_product) do |f| %>
                            
                            <div class="form-group">
                               <%=f.label :name%>
                                <%=f.text_field :name ,class: 'form-control admin_product_name', placeholder: 'Enter name' , required: 'true'%>
                            </div>
                            <div class="form-group">
                               <%=f.label :price%>
                                <%=f.number_field :price ,class: 'form-control', placeholder: 'Enter Price' , required: 'true'%>
                            </div>
                            <div class="form-group">
                               <%=f.label :discounted_price%>
                                <%=f.number_field :discounted_pric, class: 'form-control admin_product_name', placeholder: 'Discounted Price' %>
                            </div>
                            <div class="form-group">
                               <%=f.label :description%>
                                <%=f.text_field :description ,class: 'form-control', placeholder: 'deccribe' , required: 'true'%>
                            </div>
                               <div class="form-group">
                              <%= f.label :categories %>
                                <%= f.select :category_ids, options_from_collection_for_select(Admin::Category.all, :id,:name,f.object.category_ids),{}, :multiple => true ,:class=> 'select form-control',:id => 'admin_categories' %>
                            </div>
                              <div class="form-group">
                               <%=f.label :Image%>
                                <%=f.file_field :avatar ,class: 'form-control'%>
                            </div>
                            <br>
                            <div><p><%= f.submit 'Submit', class: "btn btn-default" %>
                            
                            <button type="reset" class="btn btn-default">Reset Button</button></p></div>
                        <%end%>
                    </div>
                    <!-- /.col-lg-6 (nested) -->
                    
                </div>
                <!-- /.row (nested) -->
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->

app/views/admin/products/edit.html.erb
<h1>Editing Admin Product</h1>

<%= render 'newform' %>

<%= link_to 'Show', @admin_product %> |
<%= link_to 'Back', admin_products_path %>

app/views/admin/products/index.html.erb
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header"> All Products</h1>
    </div>
    <!-- /.col-lg-12 -->
    <div class="col-lg-12"><%= link_to 'New Product', new_admin_product_path %></div>
    
</div >
<!-- /.row -->
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div  id="admin_products">
                    <%=render :partial => 'all_products'%>
                    <!-- /.table-responsive -->
                </div> 
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->


















<!-- 
<p id="notice"><%= notice %></p>

<h1>Listing Admin Products</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @admin_products.each do |admin_product| %>
      <tr>
        <td><%= link_to 'Show', admin_product %></td>
        <td><%= link_to 'Edit', edit_admin_product_path(admin_product) %></td>
        <td><%= link_to 'Destroy', admin_product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_admin_product_path %>
 -->

app/views/admin/products/new.html.erb
<h1>New Admin Product</h1>

<%= render 'newform' %>

<%= link_to 'Back', admin_products_path %>

app/views/admin/products/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_admin_product_path(@admin_product) %> |
<%= link_to 'Back', admin_products_path %>

app/views/products/_all_products.html.erb
              <% @admin_products.each do |product| %>
						 <div class="col-md-3 fashion-grid fashion-grid1 oo" >
							 <a id ="img123" href="<%=product_path(product)%>"><p></p><%= image_tag product.avatar.url(:normal) %>
								 <div class="product" id = <%= product.name%>>
									 <h3><%= product.name%></h3>
									 <p><span></span> <%= product.price %>&euro;</p>								 </div>
							 </a>
							<!--  <div class="fashion-view"><span></span>
										<div class="clearfix"></div>
									 <h4><a href="single.html">Quick View</a></h4>
							 </div> -->
						 </div>
						 <% end %>
						 <div class="clearfix"></div>

app/views/products/_product_categories.html.erb
<div class="col-md-3 side-bar">
				<div class="categories">
				<h3>CATEGORIES</h3>
				<% @admin_categories.each do |category| %>
				<%#= render 'selected_product_category'%>
						<ul>
							<li><%= link_to category.name, products_path(:category_id => category.id), :remote => true %>
</li>
						</ul>
						<%end%>	
				</div>			
			</div>

app/views/products/_selected_product_category.html.erb
<%= link_to category.name, products_path(:admin_category_id => admin_category.id), :remote => true %>

app/views/products/index.html.erb
<div class="men">
		<!-- container -->
		<div class="container">
		<div class="col-md-9 fashions">
				<div class="title">
					<h3>PRODUCTS</h3>
			</div>
				<div class="fashion-section">
				<div class="fashion-grid1" id = "productid">
					<%= render :partial => "/products/all_products" %>
					</div>
				</div>
			</div>	
			<%= render :partial => "/products/product_categories" %>
			<div class="clearfix"> </div>
		</div>
		<!-- //container -->
	</div>
	<!-- //men -->
	<!-- footer -->	
	<!-- //footer -->

app/views/products/index.js.erb
  $("#productid").html("<%= escape_javascript(render partial: '/products/all_products', locals: { admin_products: @admin_products } ) %>"); 

app/views/products/show.html.erb
<!-- header -->
	<!-- //header -->
	<!-- single -->
	<div class="single">
		<!-- container -->
		<div class="container">
			<div class="single-grids">
				<div class="col-md-9">
					<div class="single-left-left">
						<ul id="etalage" class="etalage" style="display: block; width: 300px; height: 533px;">
							<li class="etalage_thumb thumb_1" style="display: none; opacity: 0; background-image: none;">
								<a href="optionallink.html">
									<img class="etalage_thumb_image" src="/assets/d1.jpg" style="display: inline; width: 300px; height: 400px; opacity: 1;">
									<img class="etalage_source_image" src="/assets/d1.jpg" title="">
								</a>
							</li>
							<li class="etalage_thumb thumb_2" style="display: none; opacity: 0; background-image: none;">
								<img class="etalage_thumb_image" src="/assets/d2.jpg" style="display: inline; width: 300px; height: 400px; opacity: 1;">
								<img class="etalage_source_image" src="/assets/d2.jpg" title="">
							</li>
							<li class="etalage_thumb thumb_3" style="display: none; opacity: 0; background-image: none;">
								<img class="etalage_thumb_image" src="/assets/d3.jpg" style="display: inline; width: 300px; height: 400px; opacity: 1;">
								<img class="etalage_source_image" src="/assets/d3.jpg">
							</li>
						    <li class="etalage_thumb thumb_4 etalage_thumb_active" style="display: list-item; opacity: 1; background-image: none;">
								<img class="etalage_thumb_image" src="<%= @product.avatar.url(:original)%>" style="display: inline; width: 300px; height: 400px; opacity: 1;">
								<img class="etalage_source_image" src="<%= @product.avatar.url(:original)%>">
							</li>
						 <div class="clearfix"></div>		
					</div>
					<div class="single-left-right">
						<div class="single-left-info">
							<h3><%= @product.name %></h3>
							
							<p><span style="color:#000;">PRICE:</span>$<%= @product.price %></p>

						</div>
						<div class="select-size">
							
							<div class="buy-now" id= "cartid">
								<!-- <a href="#"><%# @product.id%></a> -->
								<%= render '/carts/product_cart' %>
							</div>
							<div class="wishlist">
								<!-- pop-up-box -->
								
								<!--//pop-up-box -->
								<div id="small-dialog2" class="mfp-hide">
									<h3>Create Account</h3> 
									<div class="social-sits">
										<ul>
											<li><a class="fb" href="#">Connect with Facebook</a></li>
											<li><a class="fb google" href="#">Connect with Google</a></li>
										</ul>
									</div>
									<div class="signup">
										<form>
											<input type="text" class="email" placeholder="Email" required="required" pattern="([\w-\.]+@([\w-]+\.)+[\w-]{2,4})?" />
											<input type="password" placeholder="Password" required="required" pattern=".{6,}" title="Minimum 6 characters required" autocomplete="off" />
											<input type="text" class="email" placeholder="Mobile Number" maxlength="10" pattern="[1-9]{1}\d{9}" title="Enter a valid mobile number" />
											<input type="submit"  value="Sign In"/>
										</form>
									</div>
									<div class="clearfix"> </div>
								</div>	
								
							</div>
							<div class="clearfix"> </div>
							<div class="delivery">
								
								
							</div>
						</div>
					</div>
					<div class="clearfix"> </div>
					<div class="product-details">
						<h3>PRODUCT DETAILS</h3>
						<p><%= @product.description %>
						</p>
					</div>
					<div class="related">
						<h3>RELATED PRODUCTS</h3>
						<div class="related-grids">
							<div class="related-grid">
								<div class="col-md-9 related-left">
									<div class="col-md-3 related-left-left">
										<img src="/assets/c1.jpg" alt="" />
									</div>
									<div class="col-md-9 related-left-right">
										<h5>Product Name</h5>
										<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras a est at leo dictum 
											pharetra vel sit amet tellus.
										</p>
									</div>
									<div class="clearfix"> </div>
								</div>
								<div class="col-md-3 related-right">
									<p>$ 19</p>
									<a href="#">Add to cart</a>
								</div>
								<div class="clearfix"> </div>
							</div>
							<div class="related-grid">
								<div class="col-md-9 related-left">
									<div class="col-md-3 related-left-left">
										<img src="/assets/c2.jpg" alt="" />
									</div>
									<div class="col-md-9 related-left-right">
										<h5>Product Name</h5>
										<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras a est at leo dictum 
											pharetra vel sit amet tellus.
										</p>
									</div>
									<div class="clearfix"> </div>
								</div>
								<div class="col-md-3 related-right">
									<p>$ 19</p>
									<a href="#">Add to cart</a>
								</div>
								<div class="clearfix"> </div>
							</div>
							<div class="related-grid">
								<div class="col-md-9 related-left">
									<div class="col-md-3 related-left-left">
										<img src="/assets/c3.jpg" alt="" />
									</div>
									<div class="col-md-9 related-left-right">
										<h5>Product Name</h5>
										<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras a est at leo dictum 
											pharetra vel sit amet tellus.
										</p>
									</div>
									<div class="clearfix"> </div>
								</div>
								<div class="col-md-3 related-right">
									<p>$ 19</p>
									<a href="#">Add to cart</a>
								</div>
								<div class="clearfix"> </div>
							</div>
						</div>
					</div>
				</div>
				<div class="col-md-3 side-bar">
						<div class="categories">
				<h3>CATEGORIES</h3>
				<% @admin_categories.each do |category| %>
				<%#= render 'selected_product_category'%>
						<ul>
							<li><%= link_to category.name, products_path(:category_id => category.id) %>
								</li>
						</ul>
						<%end%>	
				</div>	
					</div>
				</div>
				<div class="clearfix"> </div>
			</div>
		</div>
		<!-- //container -->
	</div>
	<!-- //single -->
	<!-- footer -->

	<!-- //footer -->